import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.scss";
import Providers from "../providers";

const geistSans = localFont({
  src: "./fonts/YekanBakhFaNum-Medium.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body data-sidebar="dark" className={`${geistSans.className} `}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
